#!/bin/sh
# [Gedit Tool]
# Name=Run win
# Shortcut=<Shift><Control>w
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=nothing


#copied from Configure command 
#(it uses another bash, aaarghh)
export configured="1";
export currdir=`pwd`;
hasscripts=`find "scripts"`;
echo "$hasscripts" > ~/log.txt;
echo "$currdir";
while `test "$hasscripts" = ""`
do
	echo "going up";
	cd ..;
	currdir=`pwd`;
	echo $currdir;
	if `test "$currdir" = "/"`
	then
		echo "can't find project files";
		configured="0";
		break;
	fi
	hasscripts=`ls "./scripts/" | grep "sc_"`;
done
if `test "$configured" = "1"`
then
	echo "success: project dir = $currdir";
else
	echo "failed";
fi
export currdir="$currdir";
export configured="$configured";

# start of real script
if [ "$configured" = "1" ]
then
	cd "$currdir"
	pwd
	make all
	proj=`./scripts/sc_getvalue.sh "solution" "project"`
	proj=`echo ${proj} | sed 's/^ *//;s/ *$//'`
	mkdir "~/wine_d/cpp-nix/${proj}"
	./scripts/sc_test.sh "${proj}"
	cd "/home/lexias/wine_d/cpp-nix/${proj}"
	wine x.exe
else
	echo "project isn't configured!!"
fi
