#!/bin/sh
# [Gedit Tool]
# Name=Source list
# Shortcut=<Control>F3
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=nothing


#copied from Configure command 
#(it uses another bash, aaarghh)
export configured="1";
export currdir=`pwd`;
hasscripts=`find "scripts"`;
echo "$hasscripts" > ~/log.txt;
echo "$currdir";
while `test "$hasscripts" = ""`
do
	echo "going up";
	cd ..;
	currdir=`pwd`;
	echo $currdir;
	if `test "$currdir" = "/"`
	then
		echo "can't find project files";
		configured="0";
		break;
	fi
	hasscripts=`ls "./scripts/" | grep "sc_"`;
done
if `test "$configured" = "1"`
then
	echo "success: project dir = $currdir";
else
	echo "failed";
fi
export currdir="$currdir";
export configured="$configured";

# start of real script
if [ "$configured" = "1" ]
then
	cd "$currdir"
	pwd
	target=`./scripts/sc_getvalue.sh "./config/source_config" "target"`
	module=`./scripts/sc_getvalue.sh "./config/source_config" "module"`
	target=`echo ${target}`
	module=`echo ${module}`
	toopen=`cat "./source/${target}/${module}/list" | sed s/"-"/"	"/g | zenity --list --text "List of sources in ${target}/${module} - gedit" --title "Sources list - gedit" --column "Source Description" --separator "	"`
	name=`echo "$toopen" | sed s/"\[[A-Za-z_]* "//g | sed s/"\([A-Za-z_]*\).*"/"\1"/g`
	if [ "${name}" = "" ]
	then
		echo "nothing choosed"
	elif [ "${name}" = "#end" ]
	then
		echo "#end choosed"
	else
		./scripts/sc_edit.sh "${name}"
	fi
else
	echo "project isn't configured!!"
fi
